apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedules-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hsnbruno6/hack-agendamentos
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: fiap-hack-agendamento.cma0pexukaru.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: Kasjo7-sevpec-jowsam
            - name: DB_NAME
              value: postgres
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '628Mi'
              cpu: '300m'
---
apiVersion: v1
kind: Service
metadata:
  name: schedules-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 3000
  type: LoadBalancer
